'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HR.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Administrator.
    '''</summary>
    Friend Shared ReadOnly Property Administrator() As String
        Get
            Return ResourceManager.GetString("Administrator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property CancelButton() As String
        Get
            Return ResourceManager.GetString("CancelButton", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Can not create an instance of this class. Please use the static members of the class..
    '''</summary>
    Friend Shared ReadOnly Property CanNotCreateClass() As String
        Get
            Return ResourceManager.GetString("CanNotCreateClass", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The current IPrincipal.IIdentiy object is of the type UserIdentity and contains the following properties:{0}.
    '''</summary>
    Friend Shared ReadOnly Property CustomUserInfo() As String
        Get
            Return ResourceManager.GetString("CustomUserInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error while checking username and  password. Please try again!.
    '''</summary>
    Friend Shared ReadOnly Property DataAccessException() As String
        Get
            Return ResourceManager.GetString("DataAccessException", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You do not belong to the neccessary security role therefore you can not complete this operation..
    '''</summary>
    Friend Shared ReadOnly Property DoNotHaveRole() As String
        Get
            Return ResourceManager.GetString("DoNotHaveRole", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Was not able to retrieve the list of security groups the user belongs to..
    '''</summary>
    Friend Shared ReadOnly Property ErrorReadingSecurityGroups() As String
        Get
            Return ResourceManager.GetString("ErrorReadingSecurityGroups", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Was not able to retrieve the list of security rights the user has..
    '''</summary>
    Friend Shared ReadOnly Property ErrorReadingSecurityRights() As String
        Get
            Return ResourceManager.GetString("ErrorReadingSecurityRights", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Was not able to retrieve the user information for the user..
    '''</summary>
    Friend Shared ReadOnly Property ErrorReadingUserInfo() As String
        Get
            Return ResourceManager.GetString("ErrorReadingUserInfo", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property excel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The current user does NOT have the permission to perform this operation..
    '''</summary>
    Friend Shared ReadOnly Property HasNotPermission() As String
        Get
            Return ResourceManager.GetString("HasNotPermission", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The current user does have the permission to perform this operation..
    '''</summary>
    Friend Shared ReadOnly Property HasPermission() As String
        Get
            Return ResourceManager.GetString("HasPermission", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Log &amp;Off.
    '''</summary>
    Friend Shared ReadOnly Property LogOff() As String
        Get
            Return ResourceManager.GetString("LogOff", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is no connection string defined. Please check the .config file!.
    '''</summary>
    Friend Shared ReadOnly Property MissingConnectionString() As String
        Get
            Return ResourceManager.GetString("MissingConnectionString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logon manager.
    '''</summary>
    Friend Shared ReadOnly Property MissingInformation() As String
        Get
            Return ResourceManager.GetString("MissingInformation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is no parameter name string defined. Please check the .config file!.
    '''</summary>
    Friend Shared ReadOnly Property MissingParamString() As String
        Get
            Return ResourceManager.GetString("MissingParamString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is no SQL command string defined. Please check the .config file!.
    '''</summary>
    Friend Shared ReadOnly Property MissingSqlString() As String
        Get
            Return ResourceManager.GetString("MissingSqlString", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modify b&amp;udget.
    '''</summary>
    Friend Shared ReadOnly Property ModifyBudget() As String
        Get
            Return ResourceManager.GetString("ModifyBudget", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modify i&amp;ventory.
    '''</summary>
    Friend Shared ReadOnly Property ModifyInventory() As String
        Get
            Return ResourceManager.GetString("ModifyInventory", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modify pro&amp;fit.
    '''</summary>
    Friend Shared ReadOnly Property ModifyProfit() As String
        Get
            Return ResourceManager.GetString("ModifyProfit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modify reve&amp;nue.
    '''</summary>
    Friend Shared ReadOnly Property ModifyRevenue() As String
        Get
            Return ResourceManager.GetString("ModifyRevenue", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter a username and password!.
    '''</summary>
    Friend Shared ReadOnly Property NoValidUserNameOrPassword() As String
        Get
            Return ResourceManager.GetString("NoValidUserNameOrPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Power user.
    '''</summary>
    Friend Shared ReadOnly Property PowerUser() As String
        Get
            Return ResourceManager.GetString("PowerUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You passed the security role check and the operation has been completed..
    '''</summary>
    Friend Shared ReadOnly Property RoleOperationCompleted() As String
        Get
            Return ResourceManager.GetString("RoleOperationCompleted", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Name.
    '''</summary>
    Friend Shared ReadOnly Property StandardPropertyName() As String
        Get
            Return ResourceManager.GetString("StandardPropertyName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The current IPrincipal.IIdentiy is of the standard IIdentity type contains the following properties:{0}.
    '''</summary>
    Friend Shared ReadOnly Property StandardUserInfo() As String
        Get
            Return ResourceManager.GetString("StandardUserInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Super admin.
    '''</summary>
    Friend Shared ReadOnly Property SuperAdministrator() As String
        Get
            Return ResourceManager.GetString("SuperAdministrator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;User.
    '''</summary>
    Friend Shared ReadOnly Property User() As String
        Get
            Return ResourceManager.GetString("User", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;User info.
    '''</summary>
    Friend Shared ReadOnly Property UserDetails() As String
        Get
            Return ResourceManager.GetString("UserDetails", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View &amp;budget.
    '''</summary>
    Friend Shared ReadOnly Property ViewBudget() As String
        Get
            Return ResourceManager.GetString("ViewBudget", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View &amp;inventory.
    '''</summary>
    Friend Shared ReadOnly Property ViewInventory() As String
        Get
            Return ResourceManager.GetString("ViewInventory", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View &amp;profit.
    '''</summary>
    Friend Shared ReadOnly Property ViewProfit() As String
        Get
            Return ResourceManager.GetString("ViewProfit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View &amp;revenue.
    '''</summary>
    Friend Shared ReadOnly Property ViewRevenue() As String
        Get
            Return ResourceManager.GetString("ViewRevenue", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The username and password you entered is not correct!.
    '''</summary>
    Friend Shared ReadOnly Property WrongUserNameAndPassword() As String
        Get
            Return ResourceManager.GetString("WrongUserNameAndPassword", resourceCulture)
        End Get
    End Property
End Class
